development:
  adapter: async

test:
  adapter: async

production:
  adapter: redis
  url: redis://redistogo:1126318de93017bb4e8e4c4b510334af@porgy.redistogo.com:11468/
  # channel_prefix: beer-or-horse-backend_production
